fmt_pretty.go
This is only my third day on Go, so this may not be the best way to fix this. Basically, #43 doesn't do a nil reference check before calling `f.length(f.feature.Background)`. I don't know if this should have been resolved further up the chain. This resolves #44.
=> Adding nil ref check

CHANGELOG.md, README.md, examples/godogs/godogs_test.go, flags.go, fmt.go, options.go, run.go, suite.go
*WORK IN PROGRESS FOR DISCUSSION, NOT READY TO MERGE*
Allow running scenarios in random order.
> This is especially helpful for detecting situations where you have state leaking between scenarios, which can cause flickering or fragile tests.
Similar to: https://www.relishapp.com/cucumber/cucumber/docs/cli/randomize
This isn't quite ready, but I wanted to open it for discussion with the maintainers prior to doing too much work on it.
If this was to be adopted, the following would likely need to be done at minimum before merging:
1. Add some sort of `--random` flag to CLI app (will leave it up to maintainers to decide what the ideal name would be?)
2. update `--help` documentation to reflect/explain this flag.
Additionally, the following might be desirable:
1. Print the random seed at the …
=> allow randomizing scenario order

CHANGELOG.md, README.md, examples/api/version.feature, features/formatter/events.feature, features/lang.feature, features/load.feature, features/multistep.feature, fmt.go, fmt_cucumber.go, fmt_events.go, fmt_junit.go, fmt_pretty.go, fmt_progress.go, fmt_progress_test.go, godog.go, run.go, run_test.go, stepdef.go, suite.go, suite_test.go
in the end should close #73 
1. [x] implement to support returning **godog.Steps** or **[]string** as multisteps on step definition func.
2. [x] add scenarios to test multistep behavior
3. [x] make some refactoring, so that **undefined** nested step, would draw correct undefined step implementation template.
4. [x] add scenarios to test undefined nested step template
=> implements convenient multistep definition

suite_context.go
This slightly relaxes the language for the SuiteContext matchers, so
that whether one starts the step with “a …” or not it will match either
way.
(It also eliminates one duplicate matcher that essentially did the same
thing without a regex.)
=> relax suite context matcher language

builder_go110.go
Since last update on go 1.10.0 and godog v0.7.7, a "dev" folder (containing the test binary named "null") was created in the current test directory (where the "godog" cmd was called) on WINDOWS machines
=> Fix windows /dev/null bug with go1.10.0

builder.go, builder_go110.go, builder_test.go, cmd/godog/main.go, colors/colors.go, colors/writer.go, fmt.go, fmt_cucumber.go, fmt_junit.go, fmt_junit_test.go, fmt_progress.go, run_test.go, suite.go, utils.go
With go 1.11 and the environment variable GO111MODULE enabled, the godog command is on error and fails to compile the `testmain` because the path used as import path is not the good one (only the module path is used).
Example of result when godog is called from the directory `module/qa`: 
`failed to compile testmain package: exit status 2 - output: /var/folders/6c/k20xl1c17735407tz10y6xs80000gn/T/go-build466142923/b001/_testmain.go:5:2: can't find import: "module"`
I hope it helps, I have also fixed some lints.
=> godog command is on error with go modules and sub-packages

flags.go, flags_test.go
This is an implementation of the feature request @ https://github.com/DATA-DOG/godog/issues/143. `BindFlags` has been updated to use any non-empty `opt` properties as default overrides. For any empty `opt` properties, the default... defaults are used.
closes #143
=> Allow overriding flag defaults in BindFlags

fmt.go, fmt_junit.go, fmt_progress.go, go.mod, run.go, run_test.go, suite.go
=> Refactored basfmt and junitFormatter to support concurrency

run.go
- A recent change caused Custom Formatters to not work with concurrency. I dont think that the godog library should not allow the usuage of concurrency on Custom Formatters. 
- https://github.com/cucumber/godog/issues/237
- https://github.com/cucumber/godog/pull/204/files#diff-12f3273da1625fbe0b8ae7f4eefe2c3cR280
=> Re enable custom formatters

_examples/api/features/version.feature
Bug then running the example of an API, a feature version need to bump to latest reported 0.8.1 #262
=> Fix Bug then running the example of an API, a feature version need to bump to latest reported 0.8.1 #262

fmt.go, fmt_junit_test.go, fmt_pretty.go, formatters_print_test.go, run.go, run_test.go, suite_context.go
=> Added concurrency support to the pretty formatter

fmt_events.go, run.go, run_test.go
=> Added concurrency support to the events formatter

fmt.go, fmt_cucumber.go, run.go, run_test.go, suite.go
=> Added concurrency support to the cucumber formatter

suite.go
=> Fixed issue with empty feature file causing nil pointer deref

README.md, _examples/api/README.md, _examples/api/api_test.go, _examples/assert-godogs/features/godogs.feature, _examples/assert-godogs/godogs_test.go, _examples/db/api_test.go, _examples/godogs/godogs_test.go, ast.go, ast_test.go, builder.go, run.go, suite.go, test_context.go, test_context_test.go
This PR changes the setup from this:
```
func FeatureContext(s *godog.Suite){
s.BeforeSuite(func() {})
s.AfterSuite(func() {})
s.BeforeScenario(func(_ *messages.Pickle) {})
s.AfterScenario(func(_ *messages.Pickle, _ error) {})
s.BeforeStep(func(_ *messages.Pickle_PickleStep) {})
s.AfterStep(func(_ *messages.Pickle_PickleStep, _ error) {})
s.Step(`^(\-*\d+\.\d+) godogs$`, godogs)
}
```
To this:
```
func InitiateSuite(ctx *godog.SuiteContext){
ctx.BeforeSuite(func() {})
ctx.AfterSuite(func() {})
}
func InitiateScenario(ctx *godog.ScenarioContext) {
ctx.BeforeScenario(func(_ *godog.Scenario) {})
ctx.AfterScenario(func(_ *godog.Scenario, _ error) {})
ctx.BeforeStep(func(_ *godog.Step) {})
ctx.AfterStep(func(_ *godog.Step, _ error) {})
ctx.Step(`^(\-*\d+\.\d+) godogs$`, godogs)
}
```
The …
=> Added the new TestSuiteInitializer and ScenarioInitializer

builder_go112_test.go, builder_go113_test.go, builder_go_module_test.go, builder_test.go
- Created a helper struct: `builderTestCase` to reuse a lot of the test code.
- Made some updates to the builder test cases so that the they can run in parallel.
- Grouped all the builder test cases in `builder_test.go` so that they all run in parallel.
=> Made the builder tests run in parallel

fmt_output_test.go, formatter-tests/cucumber/scenario_outline, formatter-tests/cucumber/scenario_with_background, formatter-tests/cucumber/single_scenario_with_passing_step, formatter-tests/cucumber/some_scenarions_including_failing, formatter-tests/cucumber/two_scenarios_with_background_fail, formatter-tests/events/scenario_outline, formatter-tests/events/scenario_with_background, formatter-tests/events/single_scenario_with_passing_step, formatter-tests/events/some_scenarions_including_failing, formatter-tests/events/two_scenarios_with_background_fail, formatter-tests/pretty/scenario_outline, formatter-tests/pretty/scenario_with_background, formatter-tests/pretty/single_scenario_with_passing_step, formatter-tests/pretty/some_scenarions_including_failing, formatter-tests/pretty/two_scenarios_with_background_fail, run_test.go, suite_context_test.go
- Copied the SuiteContext for testing with the new Context Initializers
- Added testing with TestSuite{}.Run() to fmt_output_test.go
- Added testing with TestSuite{}.Run() to run_test.go
=> Added better testing of the Context Initializers and TestSuite{}.Run()

run.go, run_test.go, suite.go
=> Fixed the broken --random flag

features/formatter/events.feature, formatter-tests/cucumber/empty, formatter-tests/cucumber/empty_with_description, formatter-tests/events/empty, formatter-tests/events/empty_with_description, formatter-tests/junit/empty, formatter-tests/junit/empty_with_description, formatter-tests/pretty/empty, formatter-tests/pretty/empty_with_description, parser.go, run.go
=> Fixed so that we don't execute features with zero scenarios

godog.go, run.go, run_test.go
=> --format junit:result.xml will now write to result.xml

formatters/fmt.go, internal/formatters/fmt_base.go, internal/formatters/fmt_events.go, internal/formatters/fmt_pretty.go, internal/formatters/fmt_progress.go, internal/models/stepdef.go, internal/models/stepdef_test.go, internal/storage/storage.go, internal/storage/storage_test.go, suite.go, test_context.go
This change would finish the move of all the needed extra exports for custom formatters to one pkg and then concentrate the exports in the base pkg to the ones needed for using godog to execute tests.
This would mean that the base of a custom formatter would look like this:
```
package customformatter
import (
"io"
"github.com/cucumber/godog"
"github.com/cucumber/godog/formatters"
"github.com/cucumber/messages-go/v10"
)
func init() {
formatters.Format("custom", "Custom formatter", customFormatterFunc)
}
func customFormatterFunc(suite string, out io.Writer) formatters.Formatter {
return &customFmt{suiteName: suite, out: out}
}
type customFmt struct {
suiteName string
out       io.Writer
}
func (f *customFmt) TestRunStarted()                                                        {}
func (f …
```
=> Moved StepDefinition to the formatters pkg

cmd/godog/internal/cmd_build.go, cmd/godog/internal/cmd_run.go, internal/flags/flags.go
=> Improved the help text of the formatter flag in the run command

internal/parser/parser.go, internal/parser/parser_test.go
Ran into trouble with pickleStepID not being unique when having the feature files on multiple paths.
In the failing scenario we have a bunch of features distributed along multiple paths.
I experienced a nil pointer dereference in the pretty printer when executing a scenario outline pickle.
The pickleStep received from `pickleStep = f.storage.MustGetPickleStep(result.PickleStepID)` was originating from a different feature from a different path
=> make pickleStepIDs unique accross multiple paths

internal/formatters/fmt_multi.go, internal/formatters/fmt_output_test.go, internal/formatters/formatter-tests/junit,pretty/empty, internal/formatters/formatter-tests/junit,pretty/empty_with_description, internal/formatters/formatter-tests/junit,pretty/empty_with_single_scenario_without_steps, internal/formatters/formatter-tests/junit,pretty/empty_with_single_scenario_without_steps_and_description, internal/formatters/formatter-tests/junit,pretty/scenario_outline, internal/formatters/formatter-tests/junit,pretty/scenario_with_background, internal/formatters/formatter-tests/junit,pretty/scenario_without_steps_with_background, internal/formatters/formatter-tests/junit,pretty/single_scenario_with_passing_step, internal/formatters/formatter-tests/junit,pretty/some_scenarions_including_failing, internal/formatters/formatter-tests/junit,pretty/two_scenarios_with_background_fail, internal/formatters/formatter-tests/junit,pretty/with_few_empty_scenarios, run.go
Resolves https://github.com/cucumber/godog/issues/346.
This PR implements formatter that can propagate events to multiple other formatters. 
Multiple formatters can be configured as comma-separated list in `Options.Format`, for example `pretty,junit:junit.xml`.
=> Use multiple formatters in the same test run

README.md, _examples/assert-godogs/godogs_test.go, _examples/godogs/godogs_test.go, cmd/godog/internal/cmd_root.go, release-notes/v0.11.0.md
This was causing way to much investigating in order for me to find
That I've only copied parts of the examples resulting in "flag".Parse
instead of pflag.Parse()
=> remove renamed imports of pflag.

run.go
And created interface GherkinFeature to allow to retrieve the main Gherkin information.
https://github.com/cucumber/godog/issues/222
Following https://github.com/cucumber/godog/pull/223 and migration to new Gherkin structure.
=> Added GetGherkinFeatures method to godog.Suite

CHANGELOG.md, README.md, features/tags.feature, go.mod, go.sum, internal/models/stepdef.go, internal/models/stepdef_test.go, run_test.go, suite_context_test.go, test_context.go, test_context_test.go
Issue: It is not possible to use function without return when
matching steps, resulting in a lot of Nil only error
returns.
Fix: Allows to provide empty result function by correctly matching
reflect Calls on step Handler.
When nothing is returned by the Handler, it will return
nil as if errors was nil.
=> feat(step_definition): Allows to define step function without return.

CHANGELOG.md, internal/models/stepdef.go
This fixes incorrect step definition output for Data Tables. 
The current code doesn't generate a correct function for Data Tables. The
`PickleStepArgument_PickleTable` type does not exist in the current `messages-go`  package.
For example:
```
Feature: Test Data Table  
Scenario: Data table                                                                                                                                                                                                                         
Given there is data:                                                                                                                                                                                                                       
| A | …
```
=> Fix step definition output for Data Tables

test_context.go
This PR adds a local type alias for `messages.GherkinDocument` to make formatter interface independent of `messages` import path.
We're going too change import path for messages some time soon (#389), that would be a breaking change for custom formatters.
With local type alias it would be possible to implement formatter that have a chance to avoid breaking change.
- Refactoring/debt (improvement to code design or tooling without changing behaviour)
No note.
No update.
=> Reduce dependency when implementing custom formatter with local alias

.circleci/config.yml, colors/ansi_others.go, colors/ansi_windows.go, internal/builder/builder_go112_test.go, internal/builder/builder_go113_test.go, release-notes/v0.12.0.md
This PR adds go1.17 to CI.
Go 1.17 is the currently latest version and godog should support it.
- Refactoring/debt (improvement to code design or tooling without changing behaviour)
No note.
No update.
=> Add go1.17 to CI tests

suite.go
There is an breaking change in `v0.12.0`, the `beforeStep` hooks are executed after `s.matchStep(step)`. Because of that, any changes in the `Step` won't be applied and taken into consideration in `matchStep()`
https://github.com/cucumber/godog/blob/afaebf26c1bc38e160c48cf921e65e52307fa3bd/suite.go#L137-L142
This behavior is newly introduced in `v0.12.0`, in the previous version, the hooks are executed before `matchStep()`
https://github.com/cucumber/godog/blob/2b426f89696bd14865efdce2f001b75be9ae9efb/suite.go#L52-L59
I see this (breaking) change is _unnecessary_ and would like to bring back the old behavior.
I don't know if we should consider this as a bug or not.
I have some logic to dynamically replace the value in the step using `beforeStep` hook. For a (stupid) example
```gherkin …
```
=> Run before step hooks before matching step

CHANGELOG.md, suite.go
Original PR: https://github.com/cucumber/godog/pull/424.
There is an breaking change in `v0.12.0`, the `beforeStep` hooks are executed after `s.matchStep(step)`. Because of that, any changes in the `Step` won't be applied and taken into consideration in `matchStep()`
https://github.com/cucumber/godog/blob/afaebf26c1bc38e160c48cf921e65e52307fa3bd/suite.go#L137-L142
This behavior is newly introduced in `v0.12.0`, in the previous version, the hooks are executed before `matchStep()`
https://github.com/cucumber/godog/blob/2b426f89696bd14865efdce2f001b75be9ae9efb/suite.go#L52-L59
I see this (breaking) change is _unnecessary_ and would like to bring back the old behavior.
I don't know if we should consider this as a bug or not.
I have some logic to dynamically replace the value in the step using …
=> Run before step hooks before matching

CONTRIBUTING.md, Makefile, README.md
A baby step towards #406.
Having paired with a new contributor on godog this week, I noticed how we don't really document how to hack on godog.
I also noticed how unwelcoming the CONTRIBUTING.md file was.
I've changed the tone to be warmer and more welcoming, and I've also made an attempt to explain what people need to do if they want to start hacking on godog.
It would be amazing to have some input here from others who have more familiarity with this codebase. For example, I noticed there's a `Makefile` with a `make test` target, but to run that I need to install golint which is deprecated. Should we still advise people to install that too, and use the `make test` target?
*Update* I figured out how to install `golint` so I've changed the instructions to model that.
=> Friendlier contributing guide

CHANGELOG.md, features/events.feature, suite.go, suite_context_test.go
This PR refactors hooks handling to improve invocation order.
This is not exactly a perfect solution for the problem, but an improvement. 
After Scenario will be invoked after step hooks of the last step in scenario or after a first failing step in scenario (all consecutive steps would have skipped status).
After Scenario will be invoked **before** skipped steps even though these steps are wrapped with step hooks.
Maybe it makes sense to disable step hooks for such steps for better consistency, but that may turn out a disruptive change of behavior.
Fixes #434
- Bug fix (non-breaking change which fixes an issue)
No note.
No update.
=> Invoke After Scenario hooks after After Step hooks

CHANGELOG.md, README.md
PR modifies the README.md to use the modern `go install` instead of the deprecated `go get` method to install the binary.
https://go.dev/doc/go-get-install-deprecation
minor documentation change
_If your change may impact future contributors, explain it here, and remember to update README.md and CONTRIBUTING.md accordingly._
_If the [Cucumber documentation](https://cucumber.io/docs/) will require an update,
submit an issue or ideally a pull request to [cucumber/docs](https://github.com/cucumber/docs/) and
reference it here._
_e.g. "Ref: cucumber/docs/pull/#99"_
=> use 'go get' instead of 'go install' to install

godog.go
Bumping the version since `godog version` reports `v0.12.0` while it should actually be `v0.12.2`.
=> Bump version

CHANGELOG.md, run.go, run_test.go, test_context.go
During [discussion](https://github.com/cucumber/godog/discussions/452) it turned out step/hooks instrumentation happens for every scenario. 
Setting up steps/hooks for each scenario may be unnecessary overhead in most cases, as step/hooks handlers are usually identical for every scenario. Improvement idea is to create "global" setup in suite initializer and use it as a base for each scenario.
So that you could use
```go
TestSuiteInitializer: func(suiteContext *godog.TestSuiteContext) {
local.RegisterSteps(suiteContext.ScenarioContext())
},
```
instead of or additionally to
```go
ScenarioInitializer: func(s *godog.ScenarioContext) {
local.RegisterSteps(s)
},
```
Also, to simplify debugging, this PR runs scenario in the same goroutine when concurrency is disabled. This allows preserving …
=> Allow suite-level configuration of steps and hooks

CHANGELOG.md, cmd/godog/internal/cmd_build.go, cmd/godog/internal/cmd_root.go, cmd/godog/internal/cmd_run.go, cmd/godog/internal/cmd_version.go, cmd/godog/main.go
Based on some conversations around testing due to #383, I've done some refactoring of the cobra command section of the code to return errors to the caller and let cobra bubble the error up to the top level call to `Execute`.
This change should allow the functions to be more easily testable instead of requiring potentially complicated test setup due to `os.Exit()` being called by the SUT.
- Refactoring/debt (improvement to code design or tooling without changing behaviour)
=> Change cmd setup to bubble up errors over exiting

CHANGELOG.md, _examples/api/README.md, _examples/api/api_test.go, _examples/assert-godogs/godogs_test.go, _examples/db/api_test.go, _examples/godogs/godogs_test.go
Remove use of deprecated methods
Have some examples up to date to continue using the framework and improve examples
- :bank: Refactoring/debt (improvement to code design or tooling without changing behaviour)
=> #459 - tests remove deprecated methods

CHANGELOG.md
* reformatted CHANGELOG.md using [`changelog`](https://github.com/cucumber/changelog).
This tool helps us to manipulate and read changelogs, but it needs to have the file in a standard format that it can read and write.
* I want to see how GitHub renders the changes.
* I know it's a pain how the username links have all been inlined, but I think it's worth it to have a standard tool for working with changelogs. Do you agree?
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
=> Reformat CHANGELOG.md using standard `changelog` CLI tool

cmd/godog/internal/cmd_run.go, cmd/godog/internal/cmd_version.go
`godog version` now prints the version number again and `godog run` will no longer print usage if a test fails.
* `godog version` wasn't printing the version number
* `godog run` was printing usage when a test failed, which cluttered up the output, and didn't seem intentional
Would you like the CHANGELOG updated for this?
=> Fix version subcommand. Do not print usage if run subcommand fails.

CHANGELOG.md, README.md
Related to #472.
This PR updates README to
* prioritize `go test` usage over CLI `godog` as it grants better flexibility and familiarity for Go developers,
* use `context.Context` in step examples for better concurrency readiness.
Running tests with CLI `godog` has limitations (#154) and is sometimes a bit obscure due to doing "magic" under the hood, using regular Go tests is (in my opinion) a better approach in general, so I think we should update documentation to encourage more `go test` usage.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-requ …
=> Update README to reflect current best practices in creating and running tests

colors/colors.go
Just typos in `colors` functions documentation.
----
=> Fix green copypasta

CHANGELOG.md, cmd/godog/internal/cmd_build.go, cmd/godog/internal/cmd_root.go, cmd/godog/internal/cmd_run.go
`godog`, `godog build` and `godog run` would issue deprecation warning before proceeding.
```
Use of godog CLI is deprecated, please use *testing.T instead.
See https://github.com/cucumber/godog/discussions/478 for details.
```
A [poll](https://github.com/cucumber/godog/discussions/478) in discussions has been active for couple of months already with general consensus in favor of CLI deprecation.
This PR makes the next step to issue a deprecation notice to improve visibility of upcoming change.
There is also chance that deprecation will be canceled if new facts will be present in related discussion.
----
*This text was originally generated from a …
=> Add deprecation notice to godog CLI

CHANGELOG.md, suite.go
After scenario hooks will no be invoked after non-last undefined step.
Originally, undefined steps that were in the middle of scenario would invoke  `s.runAfterScenarioHooks` and then proceed to next steps. This may result in multiple invocations of after scenario hooks which is incorrect behavior.
----
=> Skip undefined steps in after scenario hooks

CHANGELOG.md
CHANGELOG is prepared for a new release.
We haven't released a new version for a while and we have some helpful changes in `main`.
----
=> Update CHANGELOG.md for release v0.12.6

.github/renovate.json
This will setup Renovate with the [default Configs from the Cucumber org](https://github.com/cucumber/renovate-config). They're completely opt in but I find them to be quite sensible. With this configuration patch and minor releases that pass CI will automatically get merged without raising a PR. Major and failing builds will be raised as a PR. This should optimize the amount of manual work and notifications that needs to be done..
Note that currently Renovate has an open issue around updating transitive dependencies (https://github.com/renovatebot/renovate/issues/12999). This will cause some extra noise. Feel free to disable renovate by adding `"enabled": false` to the config file if it is too much.
The last few releases of Gherkin have been rather rocky for Go. Instead of relying on …
=> Setup Renovate with default Configs

README.md
- Correct docs example to use right keyword
----
=> docs(*): correct example

CHANGELOG.md, README.md
Closes #537 
This pull request updates documentation to prefer `go test` over the `godog` CLI in the main README example. I realize there has been [some discussion around deprecating the CLI](https://github.com/cucumber/godog/discussions/478#discussioncomment-5132776) since last checking on this, so please let me know if the deprecation information I was working off of from #478 is still accurate.
Remove `godog` CLI related details from main README example. Add notice 
If the CLI is to be deprecated or have less maintenance around it, adopters of godog should be pointed to up to date information when considering the project.
----
*This text was originally generated from a …
=> docs: prefer go test to use of godog cli in README

CHANGELOG.md, README.md, go.sum, internal/flags/options.go, internal/parser/parser.go, internal/parser/parser_test.go, internal/storage/fs.go, internal/storage/fs_test.go, run.go, run_test.go, suite_context_test.go
Allow users to supply a `fs.FS` to files from. If not provided, we will fallback to the standard `os` file operations.
As `fs.FS` is an interface it gives users flexibility beyond just the operating system's filesystem, such as mocking (see, for example, the tests. We no longer write data to `/tmp`) or at the very least, an in-memory fs. But the key feature is that it allows us to compile the feature files into an executable test binary, allowing that binary to be shipped independent from the feature files.
```go
//go:embed features/*
var featuresData embed.FS
...
var opts = godog.Options{
Paths: []string{"features"},
FS:    featureData,
}
```
Then we can just:
```sh
> go test -c ./test/integration/integration_test.go
> mv integration.test /some/random/dir
> cd /some/random/dir
> …
```
=> Use `fs.FS` abstraction for filesystem

CHANGELOG.md, _examples/go.mod, _examples/go.sum, go.mod, go.sum, suite.go
Each Scenario gets a cancellable context that is cancelled at the end of the scenario.
Cancelled context can be used to shut down mock services that are run in the scope of one Scenario (see #513)
----
=> cancel context for each scenario

.github/workflows/test.yml, internal/formatters/fmt_base.go, internal/formatters/fmt_color_tag_test.go, internal/formatters/fmt_multi.go, internal/formatters/undefined_snippets_gen.go, internal/models/stepdef_test.go, internal/storage/storage.go
We use [`staticcheck`](https://staticcheck.io/) to lint the code, and so far the binary is bundled in the repo.
This PR migrates to the official GitHub Action.
Also the issues found by `staticcheck` are fixed.
Currently, bundled binary is bloating the repo and makes it a bit harder to use newer versions of the tool.
----
=> Use staticcheck GitHub Action

test_context.go
1. ScenarioContext has methods on both value and pointer receivers, make all methods have value receivers.
2. fix the syntax error in the comment
3. remove unused function Build
make the code more cleanable, readable, more compliant with Go language specifications
- :boom: Breaking change (incompatible changes to the API)
----
=> refactor: test_context.go

CHANGELOG.md, suite.go, suite_context_test.go
* Added a test for hooks/steps sequence and final result.
* Added `ErrSkip` to skip scenario from a step.
* Fixed issue when `AfterScenario` could be invoked twice.
* Added step hooks invocation for multi steps.
Hooks invocation isn't consistent across different situations, this PR tries to improve that and make behavior less surprising.
Resolves #565.
Resolves #560.
Resolves #486.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
=> Improve hooks invocation flow

_examples/godogs/godogs.go, _examples/godogs/godogs_test.go, _examples/incorrect-project-structure/go.sum
Our example suite was implemented around a global shared resource and did not run properly with concurrency enabled. This PR uses contextualized data separation to showcase concurrency support in that example.
Fixes #572.
Nothing.
----
=> Improve example with concurrency support

internal/formatters/fmt_base_test.go, suite.go
This PR
* Updates some of the error checks with `errors.Is` for better reliability with wrapping
* Adds missing handling of step result statuses for `ErrSkip`
* Adds a test to validate formatter `Summary()` and step execution flow
#582 introduced a fix that was invisible for current test suite (tests passing before and after), while covering the fix with a regression test it turned out, `ErrSkip` is not properly reported in `Summary()`.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
=> Improve ErrSkip handling, add test for Summary and operations order

CHANGELOG.md, features/formatter/cucumber.feature, internal/formatters/fmt_cucumber.go, internal/formatters/formatter-tests/cucumber/scenario_outline
Removing line overwrite from cucumber formatter 
```
if len(pickle.AstNodeIds) == 2 {
_, row := feature.FindExample(pickle.AstNodeIds[1])
line = row.Location.Line
}
```
The above code from cucumber/godog/fmt_cucumber.go overwrites the line property values of steps in cucumber reports (for Scenario Outlines only, regular Scenarios reports look good).
As a result, the step line property corresponds to the line in the Examples section rather than to the actual location of step within the feature file.
Due to the above, external tools that process the reports and use the line property for sorting the steps, display the steps out of order.
Other officially supported cucumber implementations (java, js, python, etc.) are generating reports correctly for Scenario Outline - line property …
=> Fixes #604 - remove line overwriting for scenario outlines in cucumber formatter

README.md, RELEASING.md
Adding RELEASING guidelines.
Was hard to figure out the release process.
Nice and simple release process, just needs documenting.
----
=> Create releasing guidelines

internal/models/results.go, suite.go
- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
- :boom: Breaking change (incompatible changes to the API)
----
=> Fix step duration calculation

run.go
fix invalid memory address or nil pointer dereference when calling TestSuite RetrieveFeatures
=> fix invalid memory address or nil pointer dereference in RetrieveFeatures

.github/workflows/gorelease.yml, .github/workflows/release-assets.yml, .github/workflows/test.yml, Makefile
This PR updates CI scripts to use latest Go version and also changes Go version check in Makefile to allow minimal version.
Our CI got a bit outdated.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
No.
----
=> Update CI and Makefile

.gitignore, CHANGELOG.md, README.md, internal/formatters/fmt_cucumber.go, internal/formatters/fmt_events.go, internal/formatters/fmt_output_test.go, internal/formatters/formatter-tests/cucumber/scenario_with_attachment, internal/formatters/formatter-tests/events/scenario_with_attachment, internal/formatters/formatter-tests/features/scenario_with_attachment.feature, internal/models/results.go, suite.go
The cucumber and events formatters support the inclusion of Attachments.
The proposed API is demonstrated in the tests as  ...
func stepWithAttachment(ctx context.Context) (context.Context, error) {
ctxOut := godog.Attach(ctx,
godog.Attachment{Body: []byte("TheData1"), FileName: "TheFilename1", MediaType: "text/plain"},
godog.Attachment{Body: []byte("TheData2"), FileName: "TheFilename2", MediaType: "text/plain"},
)
return ctxOut, nil
}
https://github.com/cucumber/godog/issues/617
Want support for Attachments from steps.
This PR proposes to use the context.Context object as a means to attach content from the step.
This change involves minimal changes to patterns of use of godog API's.
I added tests for the cuke and events …
=> added support for Attachments (aka Embedddings)

CHANGELOG.md
Moved a changelog entry to the correct location 
<!---
--
=> Moved CHANGHELOG entry to correct location

CHANGELOG.md, README.md, _examples/attachments/README.md, _examples/attachments/attachments_test.go, _examples/attachments/features/attachments.feature, internal/formatters/fmt_cucumber.go, internal/formatters/fmt_output_test.go, internal/formatters/formatter-tests/cucumber/scenario_with_attachment, internal/formatters/formatter-tests/events/scenario_with_attachment, internal/formatters/formatter-tests/features/scenario_with_attachment.feature, internal/models/results.go, run_progress_test.go, suite.go
Added _example/attachments.
Added further test case for multiple calls to Attach() within a single step.
Code review comment applied - use a slice of object instead of slice of pointer 
Comments made here https://github.com/cucumber/godog/pull/623
----
=> Additional code review observations on Attach() functionality from https://github.com/cucumber/godog/pull/623

_examples/attachments/README.md, _examples/attachments/attachments_test.go
- :book: Documentation (improvements without changing code)
----
=> Minor doc and comment corrections

CHANGELOG.md, internal/formatters/fmt_output_test.go, internal/models/stepdef.go, internal/models/stepdef_test.go, run_progress_test.go, suite_context_test.go, test_context.go, test_context_test.go
This change fixes some type checks on the signatures and runtime return values of the handlers. 
This change also improves the quality of the error messages produced.
--
History ...
At some point someone changed the return type for "nested steps" handlers from []string to godog.Steps but they forgot to adjust the type checks where the handlers are registered.
They got away with this because the existing type checks were lax and unable to distinguish  []string from godog.Steps.
However,  in a couple of places in the code the value is coerced to godog.Steps and so if someone had actually returned []string then the code would blow up at run time rather than during registration. 
Additionally there were some tests around these types but they also had not been updated and the test was passing …
=> Fix some type checks on the signatures of nested step handlers

CHANGELOG.md, internal/formatters/fmt_base_test.go, suite.go, suite_context_test.go
Step text is added to the wrapped error and can help to identify the problematic step.
```
=== RUN   TestAPISuiteRun/Foo
suite.go:634: step is undefined: I should have "foo" responssssse with body
```
Currently, the error returned for an undefined step lacks details and relies on formatter context to be actionable
```
=== RUN   TestAPISuiteRun/Foo
suite.go:634: step is undefined
```
This makes it hard to understand which exact step is the issue.
No.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
=> Add details to "step is undefined" error

CHANGELOG.md, internal/models/stepdef.go, internal/models/stepdef_test.go
Currently, if a step function is defined as:
```go
ctx.Step(`^the input is "([^"]*)"$`, func(ctx context.Context, a, b string) error {
return nil
}
```
Then when executing, we get the following error because it counts `context.Context` as an expected error:
```
func expected more arguments than given: expected 3 arguments, matched 1 from step
```
This fixes the error to say
```
func expected more arguments than given: expected 2 arguments, matched 1 from step
```
Just noticed this today and thought I'd fix it.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. …
=> fix(errors): Fix expected Step argument count for steps with `context.Context`

.github/workflows/gorelease.yml, CHANGELOG.md
As per the deprecation warning and explanation at https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See https://github.com/cucumber/common/issues/2150
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
Is the changelog entry fine this way?
----
=> Replace deprecated `::set-output`

CHANGELOG.md, internal/formatters/fmt.go, internal/models/stepdef.go, suite.go, test_context.go
Pretty printing results now prints the line where the step is declared instead of the line where the handler is declared.
Printing the file and line number of handlers often produces meaningless results. For example:
* Anonymous functions: `ctx.Step("...", func () {...})` always point to line 0: `some_file_test.go:0`
* Instance receiver methods: `ctx.Step("...", instance.Method)` always point to: `<autogenerated>:1`. 
Pointing to the step declaration does require an additional click to get to the handler code, so an alternative approach would be to improve the reflection process to do a better job locating the handler code.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
This might be considered breaking if anyone is relying on the …
=> Print step declaration line instead of handler declaration line
